namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
        }
    }
    class Employee {
        int empNo;
        string name;
        decimal basic;
        short deptNo;

       
        public string Name{
            set { if (value == "")
                {
                    Console.WriteLine("Emplyee name should be not empty");
                }
                else {
                    name = value;
                }
            }
            get { return name; }
            
        }
        static int empNoGenerator = 0;

        public int EmpNo {
            set {
                empNo = ++empNoGenerator;

            }
            get {
                return empNo;
            }
        }

        public decimal Basic
        {
            set
            {
                if (value < 1000 && value > 100000)
                {
                    basic = value;
                }
                else {
                    Console.WriteLine("Basic should be range in 10000 to 100000");
                }

            }
            get
            {
                return empNo;
            }
        }

        public short DeptNo
        {
            set
            {
                if (value == 0)
                {
                    Console.WriteLine("DeptNo should be not empty");
                }
                else
                {
                    deptNo = value;
                }
            }
            get { return deptNo; }

        }

        public Employee(string name, decimal basic, short deptNo)
        {
            this.Name = name;
            this.Basic = basic;
            this.DeptNo = deptNo;
        }


    }
}


//Create a Class Employee with the following specifications

//Properties
//----------
//string Name -> no blank names should be allowed
//int EmpNo ->  must be readonly and autogenerated
//decimal Basic -> must be between some range
//short DeptNo -> must be > 0

//Methods
//-------
//decimal GetNetSalary() -> returns calculated net salary (Use any formula to get net salary based on Basic salary)


//Create constructors to accept initial values for Employee obj
//Employee o1 = new Employee("Amol", 123465, 10);
//Employee o2 = new Employee("Amol", 123465);
//Employee o3 = new Employee("Amol");
//Employee o4 = new Employee();

//EmpNo must be autogenerated ... i.e.
//first object should automatically get EmpNo 1
//second object should automatically get EmpNo 2
//third object should automatically get EmpNo 3
//...and so on...

//Test Cases
//Employee o1 = new Employee()
//Employee o2 = new Employee()
//Employee o3 = new Employee()
//cw(o1.EmpNo)
//cw(o2.EmpNo)
//cw(o3.EmpNo)

//cw(o3.EmpNo)
//cw(o2.EmpNo)
//cw(o1.EmpNo)









