// <auto-generated />
using System;
using DbFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbFirst.Migrations
{
    [DbContext(typeof(ActsJan25Context))]
    partial class ActsJan25ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbFirst.Models.Department", b =>
                {
                    b.Property<int>("DeptNo")
                        .HasColumnType("int")
                        .HasColumnName("DeptNo");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DeptName");

                    b.HasKey("DeptNo")
                        .HasName("PK__Departme__0148CAAE5E4F950B");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("DbFirst.Models.Employee", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int")
                        .HasColumnName("EmpNo");

                    b.Property<decimal>("Basic")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Basic");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int")
                        .HasColumnName("DeptNo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("EmpNo")
                        .HasName("PK__Employee__AF2D66D3616991BD");

                    b.HasIndex("DeptNo");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DbFirst.Models.Table", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("Basic")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmpNo")
                        .HasName("PK__Table__AF2D66D316FEF4FA");

                    b.ToTable("Table", (string)null);
                });

            modelBuilder.Entity("DbFirst.Models.Employee", b =>
                {
                    b.HasOne("DbFirst.Models.Department", "DeptNoNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Employees_ToTable");

                    b.Navigation("DeptNoNavigation");
                });

            modelBuilder.Entity("DbFirst.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
